add: basic commands
evdoo/parking-manager pull request #1
Opened 2023-02-21 16:46 UTC by evdoo

Completed the first task

2023-02-21 18:59 UTC, ermolnik requested changes

2023-02-21 18:59 UTC, ermolnik commented on .idea/inspectionProfiles/Project_Default.xml
> +    <option name="myName" value="Project Default" />
Этого файла не должно быть в Гите

2023-02-21 18:59 UTC, ermolnik commented on ParkingManager.iml
> +    <exclude-output />
Всей папки не должно быть в Гите

2023-02-25 11:40 UTC, evdoo commented
Первый gitignore у меня добавлял слишком мало файлов, и после стягивания проекта приходилось исправлять конфигурацию, чтобы его запустить.
Новый (который я сгенерировала), как оказалось, добавил слишком много файлов. А еще в нем в целом было много явно лишнего.
Как научиться писать gitignore без генераторов, под свой проект? :)
Пока нашла только вот это [обсуждение](https://ru.stackoverflow.com/questions/474556/%d0%a7%d1%82%d0%be-%d0%b4%d0%be%d0%bb%d0%b6%d0%bd%d0%be-%d0%b8-%d0%bd%d0%b5-%d0%b4%d0%be%d0%bb%d0%b6%d0%bd%d0%be-%d0%b1%d1%8b%d1%82%d1%8c-%d0%b2-gitignore-%d0%b4%d0%bb%d1%8f-%d0%bb%d1%8e%d0%b1%d0%be%d0%b3%d0%be-%d1%8f%d0%b7%d1%8b%d0%ba%d0%b0-%d0%b8-ide), но не могу сказать, что все в нем понимаю :)

2023-02-26 16:43 UTC, ermolnik commented on .idea/misc.xml
> +    <output url="file://$PROJECT_DIR$/out" />
Этих файлов не должно быть в Гите

2023-03-01 15:54 UTC, ermolnik approved these changes

2023-03-02 12:37 UTC, merged